### ISSUE TITLE
Wiki Updates: Anomaly Detection Transforms

### ISSUE THREAD

**Issue by shouvikmani** [SalesforceEng/Argus#101]
Please merge my changes to the Wiki. Contains descriptions of the following transforms:
- ANOMALY_DENSITY
- ANOMALY_KMEANS
- ANOMALY_RPCA
- ANOMALY_ZSCORE

Wiki: https://github.com/shouvikmani/Argus/wiki/Transforms
Repo: https://github.com/shouvikmani/Argus.wiki.git

**Comment by saaja-sfdc** [comment]
done!
