### ISSUE TITLE
Argus Web CORS issue

### ISSUE THREAD

**Issue by mehrotramudit** [SalesforceEng/Argus#53]
Argus login/authentication does not succeeds  because login request from the web app to servlet running on tomcat container is a Cross Origin HTTP request.

I have deployed the war file on tomcat-7.0.69.

![screen shot 2016-05-18 at 4 06 29 pm](https://cloud.githubusercontent.com/assets/7265877/15377972/881e63e6-1d14-11e6-8a71-aca81324f2fb.png)

**Comment by bsura** [comment]
Update your server to accept cross origin requests. Here's the link that you can follow.
https://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter

You can add it to either server.xml or argus web.xml.

**Comment by bsura** [comment]
Can we close this?

**Comment by mehrotramudit** [comment]
Thanks for your response. Closing this.
