### ISSUE TITLE
Getting Argus running does not work

### ISSUE THREAD

**Issue by numbnut** [SalesforceEng/Argus#62]
Hi,
I tried to get Argus working in a docker environment. The documentation seems to be incomplete.
Are there other documentation resources with detailed information? Especially the documentation about how to get the ArgusWeb App working is missing as far as I know. I read the wiki and had a look into the readme files. Thank you!

**Comment by bsura** [comment]
ArgusWeb is a static HTML5/Angular web resources project. Take a look at ArgusWeb Readme for information on how to get started with that. It essentially involves 4 steps: Install npm on your machine. Run npm install (this will internally call bower install for you which will download all dependencies for you). Install grunt. And use grunt replace (local/development/production) to tell ArgusWeb what endpoint to use.

**Comment by numbnut** [comment]
I did nearly the same. I installed node via nvm und than installed grunt globally. Afterwards I configured the application and launched it by invoking npm start. Npm start triggers a npm install and a bower install. When I access the Webpage on http://localhost:8080 I can see only the menu and a greeting which says "Welcome {{getRemoteUser()}}". Additionally the application gets a 404 Error on requesting selectize.js. The js console says:
```
Error: [$injector:modulerr] Failed to instantiate module argusMain due to:
[$injector:modulerr] Failed to instantiate module selectize due to:
[$injector:nomod] Module 'selectize' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.20/$injector/nomod?p0=selectize
minErr/<@http://localhost:8000/app/bower_components/angular/angular.js:63:12
module/<@http://localhost:8000/app/bower_components/angular/angular.js:1778:17
ensure@http://localhost:8000/app/bower_components/angular/angular.js:1702:38
module@http://localhost:8000/app/bower_components/angular/angular.js:1776:14
loadModules/<@http://localhost:8000/app/bower_components/angular/angular.js:4131:22
forEach@http://localhost:8000/app/bower_components/angular/angular.js:326:11
loadModules@http://localhost:8000/app/bower_components/angular/angular.js:4115:5
loadModules/<@http://localhost:8000/a
``` 
Why is this bower dependency missing? Do I have an issue with the project configuration or is there a Bug in the application?

**Comment by rajsarkapally-sfdc** [comment]
selectize path was changed. Can you please replace 	**<script src="bower_components/angular-selectize2/dist/selectize.js"></script>**  with **<script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>** in index.html file?

I will submit a pull request to correct this by eod.

**Comment by numbnut** [comment]
Hi, the bug is fixed and the front end works. Thank you very much! Besides that I have problems to get the configuration right, but I will try it again and create another issue if I don't get it right.
