### ISSUE TITLE
Please merge this WIKI

### ISSUE THREAD

**Issue by aertoria** [SalesforceEng/Argus#79]
https://github.com/aertoria/Argus.wiki.git

Thanks
To who-ever-is-admin: Follow Merge changes session at https://gist.github.com/larrybotha/10650410

**Comment by aertoria** [comment]
@saaja-sfdc 
updated for all four transform in wiki. Sorry for the confusion. I must've forked the older copy which was not complete. Let me know if it works

**Comment by saaja-sfdc** [comment]
Merged.
